language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer self-update
  
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

script:
  - vendor/bin/phpunit