language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# optionally set up exclutions and allowed failures in the matrix
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
